# Generated by Django 5.0.6 on 2024-08-01 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albom',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='albom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spotify.albom'),
            preserve_default=False,
        ),
    ]
