# Generated by Django 5.0.6 on 2024-08-15 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='artists/')),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='alboms/')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('artist', models.ManyToManyField(related_name='alboms', to='api.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, null=True)),
                ('image', models.ImageField(upload_to='songs/')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.albom')),
                ('artist', models.ManyToManyField(related_name='songs', to='api.artist')),
            ],
        ),
    ]
