# Generated by Django 5.0.6 on 2024-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status_st_tch',
            field=models.CharField(choices=[('st', 'student'), ('tch', 'teacher')], default='tch', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('st', 'student'), ('tch', 'teacher')], default='st', editable=False, max_length=4),
        ),
    ]
