# Generated by Django 5.0.6 on 2024-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_listen_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Public')], default='pb', max_length=5),
        ),
    ]
