# Generated by Django 5.0.6 on 2024-08-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teacher_managers_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='status_pb',
            new_name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='status_st_tch',
            field=models.CharField(choices=[('st', 'student'), ('tch', 'teacher')], default='st', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('df', 'draft'), ('pb', 'publish')], default='pb', max_length=4),
        ),
    ]
